### PR TITLE
Update to modern version of node-canvas

### PR DESCRIPTION
**Pull request by ghost**
Update required version of `node-canvas`, since the installation the currently required version of `node-canvas` fails to install on more modern versions of node where `node-waf` is deprecated.

### CODE REVIEW

**Comment by nikochaffin** [comment]
@tj If this could be incorporated into the `npm` module for this repo, that'd be awesome. 👍

**Comment by tj** [comment]
Woot, what's your npm username? I'll add you since I don't use this anymore

**Comment by nikochaffin** [comment]
I'm on npm as "nikochaffin" now. Although I'll be honest, I just created it, so I'm green to managing an npm package. I've just worked with a bower package or two before.

Thanks,
- Niko

**Comment by tj** [comment]
added!

**Comment by ghost** [comment]
Thanks for that! 😁

**Pull request merged**
